repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-shebang-scripts-are-executable
  - id: mixed-line-ending
    args: [--fix=auto]


- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.0
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]
